---
language: python
python: "2.7"
services:
- docker
# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install molecule

  # Check ansible version
  - molecule --version

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run molecule tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/