---
os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "nightly"
env:
  - MOLECULE=3.0.2
  - MOLECULE=2.22

services:
- docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip
install:
  # Install ansible
  - pip install molecule[docker,lint]==$MOLECULE

  # Check ansible version
  - ansible --version
  - molecule --version

script:

  # Run molecule tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/