---
os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "nightly"
env:
  - ANSIBLE=2.9.6 MOLECULE=3.0.2
  - ANSIBLE=2.8.10 MOLECULE=3.0.2
  - ANSIBLE=2.7.16 MOLECULE=3.0.2
  - ANSIBLE=2.6.20 MOLECULE=3.0.2
  - ANSIBLE=2.5.15 MOLECULE=3.0.2
  - ANSIBLE=2.4.6.0 MOLECULE=3.0.2
  - ANSIBLE=2.9.6 MOLECULE=2.2.2
  - ANSIBLE=2.8.10 MOLECULE=2.2.2
  - ANSIBLE=2.7.16 MOLECULE=2.2.2
  - ANSIBLE=2.6.20 MOLECULE=2.2.2
  - ANSIBLE=2.5.15 MOLECULE=2.2.2
  - ANSIBLE=2.4.6.0 MOLECULE=2.2.2

services:
- docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip
install:
  # Install ansible
  - pip install ansible==$ANSIBLE
  - pip install molecule[docker,lint]==$MOLECULE

  # Check ansible version
  - molecule --version

script:

  # Run molecule tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/