---
# tasks file for ansible-sssh


- include: savemoduli.yml
  static: yes
  tags: moduli
  when: moduli_generate

- include: server_keys.yml
  static: yes

- name: Limit to protocol version 2
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*Protocol.*'
    line: 'Protocol 2'
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: Enable Public Key Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PubkeyAuthentication yes'
    state: present
  notify: restart sshd

- name: Limit Key Exchange algorithms
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?KexAlgorithms .*'
    line: "KexAlgorithms {{ kex_algorithms|join(',')}}"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: Limit Ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Ciphers .*"
    line: "Ciphers {{ ciphers|join(',')}}"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: Limit Message Authentication Codes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?MACs .*"
    line: "MACs {{ macs|join(',')}}"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: Disable password based authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: restart sshd

- name: Disable Challenge Response Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*ChallengeResponseAuthentication\s*yes'
    state: absent
  notify: restart sshd
